name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: master

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libfaiss-dev librocksdb-dev

        # Install llama.cpp
        git clone https://github.com/ggerganov/llama.cpp.git /tmp/llama.cpp
        cd /tmp/llama.cpp
        make -j$(nproc)
        sudo cp libllama.so /usr/local/lib/
        sudo cp ggml.h llama.h /usr/local/include/
        sudo ldconfig


    - name: Run tests
      run: zig build test