name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        lfs: true

    - name: Setup Zig
      uses: goto-bus-stop/setup-zig@v2
      with:
        version: master

    - name: Install dependencies
      run: |
        brew install faiss llama.cpp rocksdb zig


    - name: Run tests
      run: zig build test